name: "running unit test, build docker image, deploy to ec2"
on: 
  push:
    branches:
      - dev
jobs:
  unit-test:
    name: unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-versions: 1.17.2
      - name: running unit test
        run: go test ./... -cover