name: "running unit test, build docker image, deploy to ec2"
on: 
  push:
    branches:
      - dev
jobs:
  unit-test:
    name: unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-versions: 1.17.2
      - name: running unit test
        run: go test ./... -cover
  build-push-docker:
    name: build image and push registry dockerhub
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - uses: actions/checkout@v2
      - name: build image
        run: docker build -t ystnysn/kemejaku_alterra .
      - name: login dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: push image to dockerhub
        run: docker push ystnysn/kemejaku_alterra:latest
  deployment:
    name: deploy to ec2
    runs-on: ubuntu-latest
    needs: build-push-docker
    steps:
      - uses: actions/checkout@v2
      - name: configuration ssh
        env: 
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.AWS }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/kemejaku.pem
          chmod 700 ~/.ssh/kemejaku.pem
          cat >> ~/.ssh/config << END
          Host development
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/kemejaku.pem
            StrictHostKeyChecking=no
          END
      - name: connect ec2, remove container, pull from registry, end start
        run: ssh development 'docker rm -f $(docker ps -a -q) || true && docker pull ystnysn/kemejaku_alterra:latest && docker run -d -p 8000:8000 --name kemejaku ystnysn/kemejaku_alterra:latest'




